name: nectar_ui
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # state management
  provider: ^6.0.5
  path_provider: ^2.0.13

  # database
  shared_preferences: ^2.0.18
  #firebase_storage: ^11.0.11
  #cloud_firestore: ^4.3.2
  sqflite: ^2.2.5
  json_annotation: ^4.8.0

  # network
  vexana: ^3.4.0

  # core utilities
  kartal: ^2.8.0

  # ui utilities
  flutter_svg: ^2.0.2
  cupertino_icons: ^1.0.5
  badges: ^3.0.2
  carousel_slider: ^4.2.1
  dots_indicator: ^2.1.0

  # authentication and user management
  #  firebase_core: ^2.5.0
  #  firebase_auth: ^4.2.6
  google_sign_in: ^6.0.2

  # localization 
  easy_localization: ^3.0.1
  
  # routing
  auto_route: ^5.0.4
  mobx_codegen: ^2.1.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  auto_route_generator: ^5.0.3
  build_runner: ^2.3.3
  dart_code_metrics: ^5.6.0

flutter:

  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/
    - assets/images/svg/
    - assets/images/png/
    - assets/lang/

  fonts:
    - family: Gilroy
      fonts:
        - asset: assets/fonts/Gilroy-Light.ttf
          weight: 300
        - asset: assets/fonts/Gilroy-Regular.ttf
          weight: 600
        - asset: assets/fonts/Gilroy-Medium.ttf
          weight: 700
        - asset: assets/fonts/Gilroy-SemiBold.ttf
          weight: 800
        - asset: assets/fonts/Gilroy-Bold.ttf
          weight: 900